### ISSUE TITLE
Wrong Vote Count

### ISSUE THREAD

**Issue by drsirmrpresidentfathercharles** [botwillacceptanything/botwillacceptanything#455]
The system is not counting the correct number of votes. For example, in #453, it said close after 8 votes, and then closed after 6.

**Comment by OLef1air** [comment]
After #389, and the minimum time has passed, only the minimum amount of votes for a guaranteed win is required for the PR to be merged.

**Comment by SpenserJ** [comment]
@drsirmrpresidentfathercharles As @OLef1air mentioned, at that point nothing will change in the outcome. Even if two downvotes are added, the vote would still be 65% for the change, and that 8th vote would automatically merge it. This expedites the process since there is no other result than a merge.

**Comment by drsirmrpresidentfathercharles** [comment]
Gotcha. Closing.
